import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import { useLanguage } from '../context/LanguageContext';
import { 
  FiUsers, FiFileText, FiShield, FiTrendingUp, FiSettings, 
  FiActivity, FiLock, FiDownload, FiPlus, FiX, FiCheck, 
  FiAlertCircle, FiServer, FiDatabase 
} from 'react-icons/fi';
import toast from 'react-hot-toast';
import './AdminDashboard.css';

const AdminDashboard = () => {
  const { user } = useAuth();
  const { t } = useLanguage();
  const [stats, setStats] = useState({
    totalUsers: 0,
    totalFIRs: 0,
    activeOfficers: 0,
    resolvedCases: 0,
    pendingFIRs: 0,
    rejectedFIRs: 0
  });
  const [users, setUsers] = useState([]);
  const [officers, setOfficers] = useState([]);
  const [systemHealth, setSystemHealth] = useState({
    server: 'online',
    database: 'connected',
    blockchain: 'active',
    uptime: '99.9%'
  });
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('overview');
  const [showUserModal, setShowUserModal] = useState(false);
  const [showOfficerModal, setShowOfficerModal] = useState(false);
  const [newUser, setNewUser] = useState({ name: '', email: '', phone: '', password: '', role: 'user' });
  const [newOfficer, setNewOfficer] = useState({ name: '', email: '', phone: '', password: '', badgeNumber: '' });

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      const [usersRes, firsRes, officersRes] = await Promise.all([
        axios.get('/api/admin/users'),
        axios.get('/api/admin/firs'),
        axios.get('/api/admin/officers')
      ]);
      
      setUsers(usersRes.data || []);
      setOfficers(officersRes.data || []);
      
      const firs = firsRes.data || [];
      setStats({
        totalUsers: usersRes.data?.length || 0,
        totalFIRs: firs.length,
        activeOfficers: officersRes.data?.length || 0,
        resolvedCases: firs.filter(f => f.status === 'resolved').length,
        pendingFIRs: firs.filter(f => f.status === 'pending').length,
        rejectedFIRs: firs.filter(f => f.status === 'rejected').length
      });
    } catch (error) {
      console.error('Error fetching data:', error);
      // Use placeholder data if endpoints don't exist yet
      setStats({
        totalUsers: 150,
        totalFIRs: 450,
        activeOfficers: 25,
        resolvedCases: 320,
        pendingFIRs: 45,
        rejectedFIRs: 85
      });
    } finally {
      setLoading(false);
    }
  };

  const handleAddUser = async () => {
    try {
      await axios.post('/api/admin/users', newUser);
      toast.success('User added successfully');
      setShowUserModal(false);
      setNewUser({ name: '', email: '', phone: '', password: '', role: 'user' });
      fetchData();
    } catch (error) {
      toast.error('Failed to add user');
    }
  };

  const handleAddOfficer = async () => {
    try {
      await axios.post('/api/admin/officers', newOfficer);
      toast.success('Officer added successfully');
      setShowOfficerModal(false);
      setNewOfficer({ name: '', email: '', phone: '', password: '', badgeNumber: '' });
      fetchData();
    } catch (error) {
      toast.error('Failed to add officer');
    }
  };

  const handleRemoveUser = async (userId) => {
    if (window.confirm('Are you sure you want to remove this user?')) {
      try {
        await axios.delete(`/api/admin/users/${userId}`);
        toast.success('User removed successfully');
        fetchData();
      } catch (error) {
        toast.error('Failed to remove user');
      }
    }
  };

  const handleToggleOfficerStatus = async (officerId, currentStatus) => {
    try {
      await axios.put(`/api/admin/officers/${officerId}`, { 
        approved: !currentStatus 
      });
      toast.success('Officer status updated');
      fetchData();
    } catch (error) {
      toast.error('Failed to update officer status');
    }
  };

  const generateSystemReport = () => {
    const report = `
SYSTEM ADMINISTRATION REPORT
============================

Generated: ${new Date().toLocaleString()}
Generated By: ${user?.name}

STATISTICS
----------
Total Users: ${stats.totalUsers}
Total FIRs: ${stats.totalFIRs}
Active Officers: ${stats.activeOfficers}
Resolved Cases: ${stats.resolvedCases}
Pending FIRs: ${stats.pendingFIRs}
Rejected FIRs: ${stats.rejectedFIRs}

SYSTEM HEALTH
-------------
Server Status: ${systemHealth.server}
Database Status: ${systemHealth.database}
Blockchain Status: ${systemHealth.blockchain}
Uptime: ${systemHealth.uptime}

This is an automated system report.
    `;
    
    const blob = new Blob([report], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `System-Report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
    toast.success('System report generated');
  };

  if (loading) {
    return <div className="loading">Loading...</div>;
  }

  return (
    <div className="admin-dashboard">
      <div className="dashboard-header">
        <div>
          <h2>Admin Dashboard</h2>
          <p>System overview and management</p>
        </div>
        <button className="btn-generate-report" onClick={generateSystemReport}>
          <FiDownload /> Generate Report
        </button>
      </div>

      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-icon">
            <FiUsers />
          </div>
          <div className="stat-content">
            <h3>{stats.totalUsers}</h3>
            <p>Total Users</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">
            <FiFileText />
          </div>
          <div className="stat-content">
            <h3>{stats.totalFIRs}</h3>
            <p>Total FIRs</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">
            <FiShield />
          </div>
          <div className="stat-content">
            <h3>{stats.activeOfficers}</h3>
            <p>Active Officers</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">
            <FiTrendingUp />
          </div>
          <div className="stat-content">
            <h3>{stats.resolvedCases}</h3>
            <p>Resolved Cases</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon pending">
            <FiAlertCircle />
          </div>
          <div className="stat-content">
            <h3>{stats.pendingFIRs}</h3>
            <p>Pending FIRs</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon rejected">
            <FiX />
          </div>
          <div className="stat-content">
            <h3>{stats.rejectedFIRs}</h3>
            <p>Rejected FIRs</p>
          </div>
        </div>
      </div>

      <div className="tabs-section">
        <button 
          className={`tab-btn ${activeTab === 'overview' ? 'active' : ''}`}
          onClick={() => setActiveTab('overview')}
        >
          Overview
        </button>
        <button 
          className={`tab-btn ${activeTab === 'users' ? 'active' : ''}`}
          onClick={() => setActiveTab('users')}
        >
          Manage Users
        </button>
        <button 
          className={`tab-btn ${activeTab === 'officers' ? 'active' : ''}`}
          onClick={() => setActiveTab('officers')}
        >
          Manage Officers
        </button>
        <button 
          className={`tab-btn ${activeTab === 'system' ? 'active' : ''}`}
          onClick={() => setActiveTab('system')}
        >
          System Health
        </button>
      </div>

      {activeTab === 'overview' && (
        <div className="admin-sections">
          <div className="admin-section">
            <h3>FIR Workflow Monitor</h3>
            <div className="workflow-stats">
              <div className="workflow-item">
                <span className="workflow-label">Pending</span>
                <span className="workflow-value">{stats.pendingFIRs}</span>
              </div>
              <div className="workflow-item">
                <span className="workflow-label">Under Review</span>
                <span className="workflow-value">0</span>
              </div>
              <div className="workflow-item">
                <span className="workflow-label">Approved</span>
                <span className="workflow-value">{stats.resolvedCases}</span>
              </div>
              <div className="workflow-item">
                <span className="workflow-label">Rejected</span>
                <span className="workflow-value">{stats.rejectedFIRs}</span>
              </div>
            </div>
          </div>
          <div className="admin-section">
            <h3>System Activity</h3>
            <p>Recent system activities and logs</p>
          </div>
        </div>
      )}

      {activeTab === 'users' && (
        <div className="admin-section">
          <div className="section-header">
            <h3>User Management</h3>
            <button className="btn-add" onClick={() => setShowUserModal(true)}>
              <FiPlus /> Add User
            </button>
          </div>
          <div className="table-container">
            <table className="admin-table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Role</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {users.length > 0 ? users.map((u) => (
                  <tr key={u._id}>
                    <td>{u.name}</td>
                    <td>{u.email}</td>
                    <td>{u.phone}</td>
                    <td><span className="role-badge">{u.role}</span></td>
                    <td>
                      <span className={`status-badge ${u.isOnline ? 'online' : 'offline'}`}>
                        {u.isOnline ? 'Online' : 'Offline'}
                      </span>
                    </td>
                    <td>
                      <button 
                        className="btn-remove"
                        onClick={() => handleRemoveUser(u._id)}
                      >
                        Remove
                      </button>
                    </td>
                  </tr>
                )) : (
                  <tr>
                    <td colSpan="6" className="empty-state">No users found</td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {activeTab === 'officers' && (
        <div className="admin-section">
          <div className="section-header">
            <h3>Officer Management</h3>
            <button className="btn-add" onClick={() => setShowOfficerModal(true)}>
              <FiPlus /> Add Officer
            </button>
          </div>
          <div className="table-container">
            <table className="admin-table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Badge Number</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {officers.length > 0 ? officers.map((o) => (
                  <tr key={o._id}>
                    <td>{o.name}</td>
                    <td>{o.email}</td>
                    <td>{o.badgeNumber || 'N/A'}</td>
                    <td>
                      <span className={`status-badge ${o.approved ? 'approved' : 'pending'}`}>
                        {o.approved ? 'Approved' : 'Pending'}
                      </span>
                    </td>
                    <td>
                      <button 
                        className="btn-toggle"
                        onClick={() => handleToggleOfficerStatus(o._id, o.approved)}
                      >
                        {o.approved ? 'Deactivate' : 'Approve'}
                      </button>
                    </td>
                  </tr>
                )) : (
                  <tr>
                    <td colSpan="5" className="empty-state">No officers found</td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {activeTab === 'system' && (
        <div className="admin-sections">
          <div className="admin-section">
            <h3>System Health</h3>
            <div className="health-grid">
              <div className="health-item">
                <FiServer />
                <div>
                  <h4>Server</h4>
                  <p className={`health-status ${systemHealth.server}`}>{systemHealth.server}</p>
                </div>
              </div>
              <div className="health-item">
                <FiDatabase />
                <div>
                  <h4>Database</h4>
                  <p className={`health-status ${systemHealth.database}`}>{systemHealth.database}</p>
                </div>
              </div>
              <div className="health-item">
                <FiLock />
                <div>
                  <h4>Blockchain</h4>
                  <p className={`health-status ${systemHealth.blockchain}`}>{systemHealth.blockchain}</p>
                </div>
              </div>
              <div className="health-item">
                <FiActivity />
                <div>
                  <h4>Uptime</h4>
                  <p className="health-status">{systemHealth.uptime}</p>
                </div>
              </div>
            </div>
          </div>
          <div className="admin-section">
            <h3>Blockchain Configuration</h3>
            <p>Manage blockchain node status and transaction verification</p>
            <button className="btn-secondary">Configure</button>
          </div>
          <div className="admin-section">
            <h3>System Policies</h3>
            <p>Update FIR form fields, evidence limits, and language settings</p>
            <button className="btn-secondary">Manage Policies</button>
          </div>
        </div>
      )}

      {/* Add User Modal */}
      {showUserModal && (
        <div className="modal-overlay" onClick={() => setShowUserModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <h3>Add New User</h3>
            <div className="modal-body">
              <div className="form-group">
                <label>Name</label>
                <input
                  type="text"
                  value={newUser.name}
                  onChange={(e) => setNewUser({ ...newUser, name: e.target.value })}
                />
              </div>
              <div className="form-group">
                <label>Email</label>
                <input
                  type="email"
                  value={newUser.email}
                  onChange={(e) => setNewUser({ ...newUser, email: e.target.value })}
                />
              </div>
              <div className="form-group">
                <label>Phone</label>
                <input
                  type="tel"
                  value={newUser.phone}
                  onChange={(e) => setNewUser({ ...newUser, phone: e.target.value })}
                />
              </div>
              <div className="form-group">
                <label>Password</label>
                <input
                  type="password"
                  value={newUser.password}
                  onChange={(e) => setNewUser({ ...newUser, password: e.target.value })}
                />
              </div>
              <div className="form-group">
                <label>Role</label>
                <select
                  value={newUser.role}
                  onChange={(e) => setNewUser({ ...newUser, role: e.target.value })}
                >
                  <option value="user">User</option>
                  <option value="officer">Officer</option>
                  <option value="admin">Admin</option>
                </select>
              </div>
              <div className="modal-actions">
                <button className="btn-cancel" onClick={() => setShowUserModal(false)}>
                  Cancel
                </button>
                <button className="btn-submit" onClick={handleAddUser}>
                  Add User
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Add Officer Modal */}
      {showOfficerModal && (
        <div className="modal-overlay" onClick={() => setShowOfficerModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <h3>Add New Officer</h3>
            <div className="modal-body">
              <div className="form-group">
                <label>Name</label>
                <input
                  type="text"
                  value={newOfficer.name}
                  onChange={(e) => setNewOfficer({ ...newOfficer, name: e.target.value })}
                />
              </div>
              <div className="form-group">
                <label>Email</label>
                <input
                  type="email"
                  value={newOfficer.email}
                  onChange={(e) => setNewOfficer({ ...newOfficer, email: e.target.value })}
                />
              </div>
              <div className="form-group">
                <label>Phone</label>
                <input
                  type="tel"
                  value={newOfficer.phone}
                  onChange={(e) => setNewOfficer({ ...newOfficer, phone: e.target.value })}
                />
              </div>
              <div className="form-group">
                <label>Badge Number</label>
                <input
                  type="text"
                  value={newOfficer.badgeNumber}
                  onChange={(e) => setNewOfficer({ ...newOfficer, badgeNumber: e.target.value })}
                />
              </div>
              <div className="form-group">
                <label>Password</label>
                <input
                  type="password"
                  value={newOfficer.password}
                  onChange={(e) => setNewOfficer({ ...newOfficer, password: e.target.value })}
                />
              </div>
              <div className="modal-actions">
                <button className="btn-cancel" onClick={() => setShowOfficerModal(false)}>
                  Cancel
                </button>
                <button className="btn-submit" onClick={handleAddOfficer}>
                  Add Officer
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AdminDashboard;
