import React, { createContext, useContext, useState, useEffect } from 'react';
import axios from 'axios';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    submitFIR: 'Submit FIR',
    trackFIR: 'Track FIR',
    profile: 'Profile',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    
    // Common
    welcome: 'Welcome',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    back: 'Back',
    
    // FIR
    firSubmission: 'FIR Submission',
    incidentDetails: 'Incident Details',
    complainantInfo: 'Complainant Information',
    incidentDate: 'Incident Date',
    incidentLocation: 'Incident Location',
    description: 'Description',
    status: 'Status',
    caseNumber: 'Case Number',
    blockchainHash: 'Blockchain Hash',
    
    // Status
    pending: 'Pending',
    under_review: 'Under Review',
    approved: 'Approved',
    rejected: 'Rejected',
    resolved: 'Resolved',
    
    // Profile
    myProfile: 'My Profile',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    onlineStatus: 'Online Status',
    online: 'Online',
    offline: 'Offline',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    creatingAccount: 'Creating account...',
    loggingIn: 'Logging in...',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordMinLength: 'Password must be at least 6 characters',
    
    // Stats
    totalFIRs: 'Total FIRs',
    pendingFIRs: 'Pending FIRs',
    approvedFIRs: 'Approved FIRs',
    resolvedFIRs: 'Resolved FIRs',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    submitFIR: 'FIR जमा करें',
    trackFIR: 'FIR ट्रैक करें',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉगआउट',
    login: 'लॉगिन',
    register: 'रजिस्टर',
    welcome: 'स्वागत है',
    loading: 'लोड हो रहा है...',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    submit: 'जमा करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    view: 'देखें',
    back: 'वापस',
    firSubmission: 'FIR जमा करना',
    incidentDetails: 'घटना विवरण',
    complainantInfo: 'शिकायतकर्ता जानकारी',
    incidentDate: 'घटना की तारीख',
    incidentLocation: 'घटना स्थान',
    description: 'विवरण',
    status: 'स्थिति',
    caseNumber: 'मामला संख्या',
    blockchainHash: 'ब्लॉकचेन हैश',
    pending: 'लंबित',
    under_review: 'समीक्षा के अधीन',
    approved: 'अनुमोदित',
    rejected: 'अस्वीकृत',
    resolved: 'हल',
    myProfile: 'मेरी प्रोफ़ाइल',
    name: 'नाम',
    email: 'ईमेल',
    phone: 'फोन',
    address: 'पता',
    onlineStatus: 'ऑनलाइन स्थिति',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    creatingAccount: 'खाता बनाया जा रहा है...',
    loggingIn: 'लॉग इन हो रहा है...',
    passwordsDoNotMatch: 'पासवर्ड मेल नहीं खाते',
    passwordMinLength: 'पासवर्ड कम से कम 6 वर्ण का होना चाहिए',
    totalFIRs: 'कुल FIR',
    pendingFIRs: 'लंबित FIR',
    approvedFIRs: 'अनुमोदित FIR',
    resolvedFIRs: 'हल FIR',
  },
  es: {
    dashboard: 'Panel',
    submitFIR: 'Enviar FIR',
    trackFIR: 'Rastrear FIR',
    profile: 'Perfil',
    logout: 'Cerrar sesión',
    login: 'Iniciar sesión',
    register: 'Registrarse',
    welcome: 'Bienvenido',
    loading: 'Cargando...',
    save: 'Guardar',
    cancel: 'Cancelar',
    submit: 'Enviar',
    edit: 'Editar',
    delete: 'Eliminar',
    view: 'Ver',
    back: 'Atrás',
    firSubmission: 'Envío de FIR',
    incidentDetails: 'Detalles del Incidente',
    complainantInfo: 'Información del Denunciante',
    incidentDate: 'Fecha del Incidente',
    incidentLocation: 'Ubicación del Incidente',
    description: 'Descripción',
    status: 'Estado',
    caseNumber: 'Número de Caso',
    blockchainHash: 'Hash de Blockchain',
    pending: 'Pendiente',
    under_review: 'En Revisión',
    approved: 'Aprobado',
    rejected: 'Rechazado',
    resolved: 'Resuelto',
    myProfile: 'Mi Perfil',
    name: 'Nombre',
    email: 'Correo',
    phone: 'Teléfono',
    address: 'Dirección',
    onlineStatus: 'Estado en Línea',
    online: 'En Línea',
    offline: 'Desconectado',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    creatingAccount: 'Creando cuenta...',
    loggingIn: 'Iniciando sesión...',
    passwordsDoNotMatch: 'Las contraseñas no coinciden',
    passwordMinLength: 'La contraseña debe tener al menos 6 caracteres',
    totalFIRs: 'Total de FIRs',
    pendingFIRs: 'FIRs Pendientes',
    approvedFIRs: 'FIRs Aprobados',
    resolvedFIRs: 'FIRs Resueltos',
  },
  fr: {
    dashboard: 'Tableau de bord',
    submitFIR: 'Soumettre FIR',
    trackFIR: 'Suivre FIR',
    profile: 'Profil',
    logout: 'Déconnexion',
    login: 'Connexion',
    register: 'S\'inscrire',
    welcome: 'Bienvenue',
    loading: 'Chargement...',
    save: 'Enregistrer',
    cancel: 'Annuler',
    submit: 'Soumettre',
    edit: 'Modifier',
    delete: 'Supprimer',
    view: 'Voir',
    back: 'Retour',
    firSubmission: 'Soumission FIR',
    incidentDetails: 'Détails de l\'Incident',
    complainantInfo: 'Informations du Plaignant',
    incidentDate: 'Date de l\'Incident',
    incidentLocation: 'Lieu de l\'Incident',
    description: 'Description',
    status: 'Statut',
    caseNumber: 'Numéro de Cas',
    blockchainHash: 'Hash Blockchain',
    pending: 'En Attente',
    under_review: 'En Révision',
    approved: 'Approuvé',
    rejected: 'Rejeté',
    resolved: 'Résolu',
    myProfile: 'Mon Profil',
    name: 'Nom',
    email: 'Email',
    phone: 'Téléphone',
    address: 'Adresse',
    onlineStatus: 'Statut en Ligne',
    online: 'En Ligne',
    offline: 'Hors Ligne',
    password: 'Mot de Passe',
    confirmPassword: 'Confirmer le Mot de Passe',
    creatingAccount: 'Création du compte...',
    loggingIn: 'Connexion...',
    passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
    passwordMinLength: 'Le mot de passe doit contenir au moins 6 caractères',
    totalFIRs: 'Total des FIRs',
    pendingFIRs: 'FIRs en Attente',
    approvedFIRs: 'FIRs Approuvés',
    resolvedFIRs: 'FIRs Résolus',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    submitFIR: 'إرسال البلاغ',
    trackFIR: 'تتبع البلاغ',
    profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    register: 'التسجيل',
    welcome: 'مرحباً',
    loading: 'جاري التحميل...',
    save: 'حفظ',
    cancel: 'إلغاء',
    submit: 'إرسال',
    edit: 'تعديل',
    delete: 'حذف',
    view: 'عرض',
    back: 'رجوع',
    firSubmission: 'إرسال البلاغ',
    incidentDetails: 'تفاصيل الحادث',
    complainantInfo: 'معلومات المشتكي',
    incidentDate: 'تاريخ الحادث',
    incidentLocation: 'موقع الحادث',
    description: 'الوصف',
    status: 'الحالة',
    caseNumber: 'رقم القضية',
    blockchainHash: 'رمز البلوك تشين',
    pending: 'قيد الانتظار',
    under_review: 'قيد المراجعة',
    approved: 'موافق عليه',
    rejected: 'مرفوض',
    resolved: 'تم الحل',
    myProfile: 'ملفي الشخصي',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    address: 'العنوان',
    onlineStatus: 'حالة الاتصال',
    online: 'متصل',
    offline: 'غير متصل',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    creatingAccount: 'جاري إنشاء الحساب...',
    loggingIn: 'جاري تسجيل الدخول...',
    passwordsDoNotMatch: 'كلمات المرور غير متطابقة',
    passwordMinLength: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    totalFIRs: 'إجمالي البلاغات',
    pendingFIRs: 'البلاغات المعلقة',
    approvedFIRs: 'البلاغات الموافق عليها',
    resolvedFIRs: 'البلاغات المحلولة',
  },
  zh: {
    dashboard: '仪表板',
    submitFIR: '提交FIR',
    trackFIR: '跟踪FIR',
    profile: '个人资料',
    logout: '登出',
    login: '登录',
    register: '注册',
    welcome: '欢迎',
    loading: '加载中...',
    save: '保存',
    cancel: '取消',
    submit: '提交',
    edit: '编辑',
    delete: '删除',
    view: '查看',
    back: '返回',
    firSubmission: 'FIR提交',
    incidentDetails: '事件详情',
    complainantInfo: '投诉人信息',
    incidentDate: '事件日期',
    incidentLocation: '事件地点',
    description: '描述',
    status: '状态',
    caseNumber: '案件编号',
    blockchainHash: '区块链哈希',
    pending: '待处理',
    under_review: '审核中',
    approved: '已批准',
    rejected: '已拒绝',
    resolved: '已解决',
    myProfile: '我的资料',
    name: '姓名',
    email: '电子邮件',
    phone: '电话',
    address: '地址',
    onlineStatus: '在线状态',
    online: '在线',
    offline: '离线',
    password: '密码',
    confirmPassword: '确认密码',
    creatingAccount: '正在创建账户...',
    loggingIn: '正在登录...',
    passwordsDoNotMatch: '密码不匹配',
    passwordMinLength: '密码至少需要6个字符',
    totalFIRs: '总FIR数',
    pendingFIRs: '待处理FIR',
    approvedFIRs: '已批准FIR',
    resolvedFIRs: '已解决FIR',
  },
  de: {
    dashboard: 'Dashboard',
    submitFIR: 'FIR einreichen',
    trackFIR: 'FIR verfolgen',
    profile: 'Profil',
    logout: 'Abmelden',
    login: 'Anmelden',
    register: 'Registrieren',
    welcome: 'Willkommen',
    loading: 'Lädt...',
    save: 'Speichern',
    cancel: 'Abbrechen',
    submit: 'Einreichen',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    view: 'Ansehen',
    back: 'Zurück',
    firSubmission: 'FIR-Einreichung',
    incidentDetails: 'Vorfall-Details',
    complainantInfo: 'Beschwerdeführer-Informationen',
    incidentDate: 'Vorfallsdatum',
    incidentLocation: 'Vorfallsort',
    description: 'Beschreibung',
    status: 'Status',
    caseNumber: 'Fallnummer',
    blockchainHash: 'Blockchain-Hash',
    pending: 'Ausstehend',
    under_review: 'In Prüfung',
    approved: 'Genehmigt',
    rejected: 'Abgelehnt',
    resolved: 'Gelöst',
    myProfile: 'Mein Profil',
    name: 'Name',
    email: 'E-Mail',
    phone: 'Telefon',
    address: 'Adresse',
    onlineStatus: 'Online-Status',
    online: 'Online',
    offline: 'Offline',
    password: 'Passwort',
    confirmPassword: 'Passwort bestätigen',
    creatingAccount: 'Konto wird erstellt...',
    loggingIn: 'Anmeldung...',
    passwordsDoNotMatch: 'Passwörter stimmen nicht überein',
    passwordMinLength: 'Passwort muss mindestens 6 Zeichen lang sein',
    totalFIRs: 'Gesamt FIRs',
    pendingFIRs: 'Ausstehende FIRs',
    approvedFIRs: 'Genehmigte FIRs',
    resolvedFIRs: 'Gelöste FIRs',
  },
  ja: {
    dashboard: 'ダッシュボード',
    submitFIR: 'FIRを提出',
    trackFIR: 'FIRを追跡',
    profile: 'プロフィール',
    logout: 'ログアウト',
    login: 'ログイン',
    register: '登録',
    welcome: 'ようこそ',
    loading: '読み込み中...',
    save: '保存',
    cancel: 'キャンセル',
    submit: '提出',
    edit: '編集',
    delete: '削除',
    view: '表示',
    back: '戻る',
    firSubmission: 'FIR提出',
    incidentDetails: '事件の詳細',
    complainantInfo: '申立人情報',
    incidentDate: '事件日',
    incidentLocation: '事件場所',
    description: '説明',
    status: 'ステータス',
    caseNumber: 'ケース番号',
    blockchainHash: 'ブロックチェーンハッシュ',
    pending: '保留中',
    under_review: '審査中',
    approved: '承認済み',
    rejected: '拒否',
    resolved: '解決済み',
    myProfile: 'マイプロフィール',
    name: '名前',
    email: 'メール',
    phone: '電話',
    address: '住所',
    onlineStatus: 'オンライン状態',
    online: 'オンライン',
    offline: 'オフライン',
    password: 'パスワード',
    confirmPassword: 'パスワード確認',
    creatingAccount: 'アカウント作成中...',
    loggingIn: 'ログイン中...',
    passwordsDoNotMatch: 'パスワードが一致しません',
    passwordMinLength: 'パスワードは6文字以上である必要があります',
    totalFIRs: '総FIR数',
    pendingFIRs: '保留中のFIR',
    approvedFIRs: '承認済みFIR',
    resolvedFIRs: '解決済みFIR',
  },
  pt: {
    dashboard: 'Painel',
    submitFIR: 'Enviar FIR',
    trackFIR: 'Rastrear FIR',
    profile: 'Perfil',
    logout: 'Sair',
    login: 'Entrar',
    register: 'Registrar',
    welcome: 'Bem-vindo',
    loading: 'Carregando...',
    save: 'Salvar',
    cancel: 'Cancelar',
    submit: 'Enviar',
    edit: 'Editar',
    delete: 'Excluir',
    view: 'Ver',
    back: 'Voltar',
    firSubmission: 'Envio de FIR',
    incidentDetails: 'Detalhes do Incidente',
    complainantInfo: 'Informações do Reclamante',
    incidentDate: 'Data do Incidente',
    incidentLocation: 'Local do Incidente',
    description: 'Descrição',
    status: 'Status',
    caseNumber: 'Número do Caso',
    blockchainHash: 'Hash Blockchain',
    pending: 'Pendente',
    under_review: 'Em Revisão',
    approved: 'Aprovado',
    rejected: 'Rejeitado',
    resolved: 'Resolvido',
    myProfile: 'Meu Perfil',
    name: 'Nome',
    email: 'Email',
    phone: 'Telefone',
    address: 'Endereço',
    onlineStatus: 'Status Online',
    online: 'Online',
    offline: 'Offline',
    password: 'Senha',
    confirmPassword: 'Confirmar Senha',
    creatingAccount: 'Criando conta...',
    loggingIn: 'Entrando...',
    passwordsDoNotMatch: 'As senhas não coincidem',
    passwordMinLength: 'A senha deve ter pelo menos 6 caracteres',
    totalFIRs: 'Total de FIRs',
    pendingFIRs: 'FIRs Pendentes',
    approvedFIRs: 'FIRs Aprovados',
    resolvedFIRs: 'FIRs Resolvidos',
  },
  ru: {
    dashboard: 'Панель управления',
    submitFIR: 'Отправить FIR',
    trackFIR: 'Отследить FIR',
    profile: 'Профиль',
    logout: 'Выйти',
    login: 'Войти',
    register: 'Регистрация',
    welcome: 'Добро пожаловать',
    loading: 'Загрузка...',
    save: 'Сохранить',
    cancel: 'Отмена',
    submit: 'Отправить',
    edit: 'Редактировать',
    delete: 'Удалить',
    view: 'Просмотр',
    back: 'Назад',
    firSubmission: 'Отправка FIR',
    incidentDetails: 'Детали Инцидента',
    complainantInfo: 'Информация о Заявителе',
    incidentDate: 'Дата Инцидента',
    incidentLocation: 'Место Инцидента',
    description: 'Описание',
    status: 'Статус',
    caseNumber: 'Номер Дела',
    blockchainHash: 'Хеш Blockchain',
    pending: 'В Ожидании',
    under_review: 'На Рассмотрении',
    approved: 'Одобрено',
    rejected: 'Отклонено',
    resolved: 'Решено',
    myProfile: 'Мой Профиль',
    name: 'Имя',
    email: 'Email',
    phone: 'Телефон',
    address: 'Адрес',
    onlineStatus: 'Статус Онлайн',
    online: 'Онлайн',
    offline: 'Офлайн',
    password: 'Пароль',
    confirmPassword: 'Подтвердить Пароль',
    creatingAccount: 'Создание аккаунта...',
    loggingIn: 'Вход...',
    passwordsDoNotMatch: 'Пароли не совпадают',
    passwordMinLength: 'Пароль должен содержать не менее 6 символов',
    totalFIRs: 'Всего FIR',
    pendingFIRs: 'Ожидающие FIR',
    approvedFIRs: 'Одобренные FIR',
    resolvedFIRs: 'Решенные FIR',
  }
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLang = localStorage.getItem('language');
    return savedLang || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);

    // Update language in database if user is logged in
    const token = localStorage.getItem('token');
    if (token) {
      axios.put(
        '/api/user/profile',
        { language },
        { headers: { Authorization: `Bearer ${token}` } }
      ).catch(err => console.error('Failed to update language:', err));
    }
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
